name: kmbart
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38he30daa8_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.10=he6710b0_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.1=217
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.19.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.17.2=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=he6710b0_1
  - markupsafe=1.1.1=py38h7b6447c_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.0=py38hfd86e86_0
  - numpy=1.19.1=py38hbc911f0_0
  - numpy-base=1.19.1=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.4=py_0
  - pandoc=2.11=hb0f4dca_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.1.1=py38_1
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pycparser=2.20=py_2
  - pygments=2.7.2=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - python=3.8.3=hcff3b4d_2
  - python-dateutil=2.8.1=py_0
  - pytorch=1.6.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h7b6447c_0
  - setuptools=49.2.0=py38_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.32.3=h62c20be_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py38_cu101
  - traitlets=5.0.5=py_0
  - wcwidth=0.2.5=py_0
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.11.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - cython==0.29.21
    - defusedxml==0.6.0
    - entrypoints==0.3
    - filelock==3.0.12
    - fvcore==0.1.2.post20201030
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.33.2
    - idna==2.10
    - ipython-genutils==0.2.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - markdown==3.3.3
    - matplotlib==3.3.2
    - nest-asyncio==1.4.2
    - notebook==6.1.5
    - oauthlib==3.1.0
    - opencv-python==4.4.0.44
    - pandocfilters==1.4.3
    - parso==0.7.1
    - pillow==6.2.2
    - portalocker==2.0.0
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pyzmq==19.0.2
    - regex==2020.10.28
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - send2trash==1.5.0
    - sentencepiece==0.1.94
    - tabulate==0.8.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - terminado==0.9.1
    - tokenizers==0.8.1rc1
    - tornado==6.1
    - tqdm==4.51.0
    - transformers==3.0.2
    - urllib3==1.25.11
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - yacs==0.1.8
